enum GamePhases {
  GAME_CREATED = 'GAME_CREATED',
  WAITING_FOR_PLAYERS = 'WAITING_FOR_PLAYERS',
  COUNTDOWN = 'COUNTDOWN',
  RUNNING = 'RUNNING',
  FINISHED = 'FINISHED',
}

export default GamePhases;
